// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	MsgEnum
	LoginRequest
	LoginResponse
	PlayerRegisterRequest
	PlayerRegisterResponse
	ChatRequest
	ChatResponse
	MatchGameRequest
	MatchGameResponse
	InviteFriendRequest
	InviteFriendResponse
	ReceiverFriendRequest
	ReceiverFriendResponse
	InvitePlayGameRequest
	InvitePlayGameResponse
	ReceiverPlayGameRequest
	ReceiverPlayGameResponse
	FriendListRequest
	FriendListRespose
	DeleteFriendRequest
	DeleteFriendResponse
	ChatMessageInfo
	PlayerInfo
	InviteFriendInfo
	ReceiverFriendInfo
	InvitePlayGameInfo
	ReceiverPlayGameInfo
	MatchGameInfo
	DeleteFriendInfo
	ChessPoint
	ChessStack
	ListChessStacks
	NowChessNums
	NowChessCount
	FinalStatistics
	PutChessReq
	PutChessRes
	RandomPlayerType
	NowCanPutType
	ChessBoardRule
	ChessRuleSetReq
	ChessRuleSetRes
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrCodeType int32

const (
	ErrCodeType_Success                      ErrCodeType = 0
	ErrCodeType_RepeatedLoginError           ErrCodeType = 1
	ErrCodeType_AccountExistError            ErrCodeType = 2
	ErrCodeType_AccountNotExistError         ErrCodeType = 3
	ErrCodeType_AccountOrPasswdNotMatchError ErrCodeType = 4
	ErrCodeType_MysqlError                   ErrCodeType = 5
	ErrCodeType_PlayerOfflineError           ErrCodeType = 6
	ErrCodeType_RoomNotExistError            ErrCodeType = 7
	ErrCodeType_ProtoPacketFormatError       ErrCodeType = 8
	ErrCodeType_PlayerPlayingGameError       ErrCodeType = 9
	ErrCodeType_InviterFriendListLimitError  ErrCodeType = 10
	ErrCodeType_InviteeFriendListLimitError  ErrCodeType = 11
	ErrCodeType_PlayerLeaveRoomError         ErrCodeType = 12
)

var ErrCodeType_name = map[int32]string{
	0:  "Success",
	1:  "RepeatedLoginError",
	2:  "AccountExistError",
	3:  "AccountNotExistError",
	4:  "AccountOrPasswdNotMatchError",
	5:  "MysqlError",
	6:  "PlayerOfflineError",
	7:  "RoomNotExistError",
	8:  "ProtoPacketFormatError",
	9:  "PlayerPlayingGameError",
	10: "InviterFriendListLimitError",
	11: "InviteeFriendListLimitError",
	12: "PlayerLeaveRoomError",
}
var ErrCodeType_value = map[string]int32{
	"Success":                      0,
	"RepeatedLoginError":           1,
	"AccountExistError":            2,
	"AccountNotExistError":         3,
	"AccountOrPasswdNotMatchError": 4,
	"MysqlError":                   5,
	"PlayerOfflineError":           6,
	"RoomNotExistError":            7,
	"ProtoPacketFormatError":       8,
	"PlayerPlayingGameError":       9,
	"InviterFriendListLimitError":  10,
	"InviteeFriendListLimitError":  11,
	"PlayerLeaveRoomError":         12,
}

func (x ErrCodeType) Enum() *ErrCodeType {
	p := new(ErrCodeType)
	*p = x
	return p
}
func (x ErrCodeType) String() string {
	return proto.EnumName(ErrCodeType_name, int32(x))
}
func (x *ErrCodeType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrCodeType_value, data, "ErrCodeType")
	if err != nil {
		return err
	}
	*x = ErrCodeType(value)
	return nil
}
func (ErrCodeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MsgEnum_MsgType int32

const (
	// 客户端向服务器请求包
	MsgEnum_PlayerRegisterRequestTag    MsgEnum_MsgType = 1
	MsgEnum_PlayerRegisterResponseTag   MsgEnum_MsgType = 2
	MsgEnum_LoginRequestTag             MsgEnum_MsgType = 3
	MsgEnum_LoginResponseTag            MsgEnum_MsgType = 4
	MsgEnum_ChatRequestTag              MsgEnum_MsgType = 5
	MsgEnum_ChatResponseTag             MsgEnum_MsgType = 6
	MsgEnum_MatchGameRequestTag         MsgEnum_MsgType = 7
	MsgEnum_MatchGameResponseTag        MsgEnum_MsgType = 8
	MsgEnum_InviteFriendRequestTag      MsgEnum_MsgType = 9
	MsgEnum_InviteFriendResponseTag     MsgEnum_MsgType = 10
	MsgEnum_ReceiverFriendRequestTag    MsgEnum_MsgType = 11
	MsgEnum_ReceiverFriendResponseTag   MsgEnum_MsgType = 12
	MsgEnum_InvitePlayGameRequestTag    MsgEnum_MsgType = 13
	MsgEnum_InvitePlayGameResponseTag   MsgEnum_MsgType = 14
	MsgEnum_ReceiverPlayGameRequestTag  MsgEnum_MsgType = 15
	MsgEnum_ReceiverPlayGameResponseTag MsgEnum_MsgType = 16
	MsgEnum_FriendListRequestTag        MsgEnum_MsgType = 17
	MsgEnum_FriendListResponseTag       MsgEnum_MsgType = 18
	MsgEnum_DeleteFriendRequestTag      MsgEnum_MsgType = 19
	MsgEnum_DeleteFriendResponseTag     MsgEnum_MsgType = 20
	MsgEnum_ChessRuleSetReqTag          MsgEnum_MsgType = 21
	MsgEnum_ChessRuleSetResTag          MsgEnum_MsgType = 22
	MsgEnum_PutChessReqTag              MsgEnum_MsgType = 23
	MsgEnum_PutChessResTag              MsgEnum_MsgType = 24
	// 服务器转发给客户端的包
	MsgEnum_ChatMessageInfoTag      MsgEnum_MsgType = 101
	MsgEnum_PlayerInfoTag           MsgEnum_MsgType = 102
	MsgEnum_InviteFriendInfoTag     MsgEnum_MsgType = 103
	MsgEnum_ReceiverFriendInfoTag   MsgEnum_MsgType = 104
	MsgEnum_InvitePlayGameInfoTag   MsgEnum_MsgType = 105
	MsgEnum_ReceiverPlayGameInfoTag MsgEnum_MsgType = 106
	MsgEnum_MatchGameInfoTag        MsgEnum_MsgType = 107
	MsgEnum_DeleteFriendInfoTag     MsgEnum_MsgType = 108
	MsgEnum_RandomPlayerTypeTag     MsgEnum_MsgType = 201
	MsgEnum_NowCanPutTypeTag        MsgEnum_MsgType = 202
	MsgEnum_FinalStatisticsTag      MsgEnum_MsgType = 203
)

var MsgEnum_MsgType_name = map[int32]string{
	1:   "PlayerRegisterRequestTag",
	2:   "PlayerRegisterResponseTag",
	3:   "LoginRequestTag",
	4:   "LoginResponseTag",
	5:   "ChatRequestTag",
	6:   "ChatResponseTag",
	7:   "MatchGameRequestTag",
	8:   "MatchGameResponseTag",
	9:   "InviteFriendRequestTag",
	10:  "InviteFriendResponseTag",
	11:  "ReceiverFriendRequestTag",
	12:  "ReceiverFriendResponseTag",
	13:  "InvitePlayGameRequestTag",
	14:  "InvitePlayGameResponseTag",
	15:  "ReceiverPlayGameRequestTag",
	16:  "ReceiverPlayGameResponseTag",
	17:  "FriendListRequestTag",
	18:  "FriendListResponseTag",
	19:  "DeleteFriendRequestTag",
	20:  "DeleteFriendResponseTag",
	21:  "ChessRuleSetReqTag",
	22:  "ChessRuleSetResTag",
	23:  "PutChessReqTag",
	24:  "PutChessResTag",
	101: "ChatMessageInfoTag",
	102: "PlayerInfoTag",
	103: "InviteFriendInfoTag",
	104: "ReceiverFriendInfoTag",
	105: "InvitePlayGameInfoTag",
	106: "ReceiverPlayGameInfoTag",
	107: "MatchGameInfoTag",
	108: "DeleteFriendInfoTag",
	201: "RandomPlayerTypeTag",
	202: "NowCanPutTypeTag",
	203: "FinalStatisticsTag",
}
var MsgEnum_MsgType_value = map[string]int32{
	"PlayerRegisterRequestTag":    1,
	"PlayerRegisterResponseTag":   2,
	"LoginRequestTag":             3,
	"LoginResponseTag":            4,
	"ChatRequestTag":              5,
	"ChatResponseTag":             6,
	"MatchGameRequestTag":         7,
	"MatchGameResponseTag":        8,
	"InviteFriendRequestTag":      9,
	"InviteFriendResponseTag":     10,
	"ReceiverFriendRequestTag":    11,
	"ReceiverFriendResponseTag":   12,
	"InvitePlayGameRequestTag":    13,
	"InvitePlayGameResponseTag":   14,
	"ReceiverPlayGameRequestTag":  15,
	"ReceiverPlayGameResponseTag": 16,
	"FriendListRequestTag":        17,
	"FriendListResponseTag":       18,
	"DeleteFriendRequestTag":      19,
	"DeleteFriendResponseTag":     20,
	"ChessRuleSetReqTag":          21,
	"ChessRuleSetResTag":          22,
	"PutChessReqTag":              23,
	"PutChessResTag":              24,
	"ChatMessageInfoTag":          101,
	"PlayerInfoTag":               102,
	"InviteFriendInfoTag":         103,
	"ReceiverFriendInfoTag":       104,
	"InvitePlayGameInfoTag":       105,
	"ReceiverPlayGameInfoTag":     106,
	"MatchGameInfoTag":            107,
	"DeleteFriendInfoTag":         108,
	"RandomPlayerTypeTag":         201,
	"NowCanPutTypeTag":            202,
	"FinalStatisticsTag":          203,
}

func (x MsgEnum_MsgType) Enum() *MsgEnum_MsgType {
	p := new(MsgEnum_MsgType)
	*p = x
	return p
}
func (x MsgEnum_MsgType) String() string {
	return proto.EnumName(MsgEnum_MsgType_name, int32(x))
}
func (x *MsgEnum_MsgType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MsgEnum_MsgType_value, data, "MsgEnum_MsgType")
	if err != nil {
		return err
	}
	*x = MsgEnum_MsgType(value)
	return nil
}
func (MsgEnum_MsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type MsgEnum struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MsgEnum) Reset()                    { *m = MsgEnum{} }
func (m *MsgEnum) String() string            { return proto.CompactTextString(m) }
func (*MsgEnum) ProtoMessage()               {}
func (*MsgEnum) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// client登录消息
type LoginRequest struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Passwd           *string `protobuf:"bytes,2,req,name=passwd" json:"passwd,omitempty"`
	Kind             *int32  `protobuf:"varint,3,req,name=kind" json:"kind,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginRequest) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *LoginRequest) GetPasswd() string {
	if m != nil && m.Passwd != nil {
		return *m.Passwd
	}
	return ""
}

func (m *LoginRequest) GetKind() int32 {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return 0
}

// client登录消息回复
type LoginResponse struct {
	Success          *ErrCodeType `protobuf:"varint,1,req,name=success,enum=protobuf.ErrCodeType" json:"success,omitempty"`
	Info             *PlayerInfo  `protobuf:"bytes,2,req,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginResponse) GetSuccess() ErrCodeType {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return ErrCodeType_Success
}

func (m *LoginResponse) GetInfo() *PlayerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// client 注册的消息
type PlayerRegisterRequest struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Passwd           *string `protobuf:"bytes,3,req,name=passwd" json:"passwd,omitempty"`
	Icon             *int32  `protobuf:"varint,4,req,name=icon" json:"icon,omitempty"`
	Sex              *int32  `protobuf:"varint,5,req,name=sex" json:"sex,omitempty"`
	Autograph        *string `protobuf:"bytes,6,req,name=autograph" json:"autograph,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerRegisterRequest) Reset()                    { *m = PlayerRegisterRequest{} }
func (m *PlayerRegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*PlayerRegisterRequest) ProtoMessage()               {}
func (*PlayerRegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PlayerRegisterRequest) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *PlayerRegisterRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PlayerRegisterRequest) GetPasswd() string {
	if m != nil && m.Passwd != nil {
		return *m.Passwd
	}
	return ""
}

func (m *PlayerRegisterRequest) GetIcon() int32 {
	if m != nil && m.Icon != nil {
		return *m.Icon
	}
	return 0
}

func (m *PlayerRegisterRequest) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *PlayerRegisterRequest) GetAutograph() string {
	if m != nil && m.Autograph != nil {
		return *m.Autograph
	}
	return ""
}

type PlayerRegisterResponse struct {
	Success          *ErrCodeType `protobuf:"varint,1,req,name=success,enum=protobuf.ErrCodeType" json:"success,omitempty"`
	Userid           *int32       `protobuf:"varint,2,req,name=userid" json:"userid,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *PlayerRegisterResponse) Reset()                    { *m = PlayerRegisterResponse{} }
func (m *PlayerRegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*PlayerRegisterResponse) ProtoMessage()               {}
func (*PlayerRegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PlayerRegisterResponse) GetSuccess() ErrCodeType {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return ErrCodeType_Success
}

func (m *PlayerRegisterResponse) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

type ChatRequest struct {
	Info             *ChatMessageInfo `protobuf:"bytes,1,req,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ChatRequest) Reset()                    { *m = ChatRequest{} }
func (m *ChatRequest) String() string            { return proto.CompactTextString(m) }
func (*ChatRequest) ProtoMessage()               {}
func (*ChatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ChatRequest) GetInfo() *ChatMessageInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ChatResponse struct {
	Success          *ErrCodeType `protobuf:"varint,1,req,name=success,enum=protobuf.ErrCodeType" json:"success,omitempty"`
	Timestamp        *int32       `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ChatResponse) Reset()                    { *m = ChatResponse{} }
func (m *ChatResponse) String() string            { return proto.CompactTextString(m) }
func (*ChatResponse) ProtoMessage()               {}
func (*ChatResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ChatResponse) GetSuccess() ErrCodeType {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return ErrCodeType_Success
}

func (m *ChatResponse) GetTimestamp() int32 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type MatchGameRequest struct {
	Userid           *int32 `protobuf:"varint,1,req,name=userid" json:"userid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MatchGameRequest) Reset()                    { *m = MatchGameRequest{} }
func (m *MatchGameRequest) String() string            { return proto.CompactTextString(m) }
func (*MatchGameRequest) ProtoMessage()               {}
func (*MatchGameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MatchGameRequest) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

type MatchGameResponse struct {
	Success          *ErrCodeType `protobuf:"varint,1,req,name=success,enum=protobuf.ErrCodeType" json:"success,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *MatchGameResponse) Reset()                    { *m = MatchGameResponse{} }
func (m *MatchGameResponse) String() string            { return proto.CompactTextString(m) }
func (*MatchGameResponse) ProtoMessage()               {}
func (*MatchGameResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MatchGameResponse) GetSuccess() ErrCodeType {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return ErrCodeType_Success
}

type InviteFriendRequest struct {
	Userid           *int32            `protobuf:"varint,1,req,name=userid" json:"userid,omitempty"`
	Info             *InviteFriendInfo `protobuf:"bytes,2,req,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *InviteFriendRequest) Reset()                    { *m = InviteFriendRequest{} }
func (m *InviteFriendRequest) String() string            { return proto.CompactTextString(m) }
func (*InviteFriendRequest) ProtoMessage()               {}
func (*InviteFriendRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *InviteFriendRequest) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *InviteFriendRequest) GetInfo() *InviteFriendInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type InviteFriendResponse struct {
	Success          *ErrCodeType `protobuf:"varint,1,req,name=success,enum=protobuf.ErrCodeType" json:"success,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *InviteFriendResponse) Reset()                    { *m = InviteFriendResponse{} }
func (m *InviteFriendResponse) String() string            { return proto.CompactTextString(m) }
func (*InviteFriendResponse) ProtoMessage()               {}
func (*InviteFriendResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *InviteFriendResponse) GetSuccess() ErrCodeType {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return ErrCodeType_Success
}

type ReceiverFriendRequest struct {
	Userid           *int32              `protobuf:"varint,1,req,name=userid" json:"userid,omitempty"`
	Info             *ReceiverFriendInfo `protobuf:"bytes,2,req,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ReceiverFriendRequest) Reset()                    { *m = ReceiverFriendRequest{} }
func (m *ReceiverFriendRequest) String() string            { return proto.CompactTextString(m) }
func (*ReceiverFriendRequest) ProtoMessage()               {}
func (*ReceiverFriendRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ReceiverFriendRequest) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *ReceiverFriendRequest) GetInfo() *ReceiverFriendInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReceiverFriendResponse struct {
	Success          *ErrCodeType `protobuf:"varint,1,req,name=success,enum=protobuf.ErrCodeType" json:"success,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ReceiverFriendResponse) Reset()                    { *m = ReceiverFriendResponse{} }
func (m *ReceiverFriendResponse) String() string            { return proto.CompactTextString(m) }
func (*ReceiverFriendResponse) ProtoMessage()               {}
func (*ReceiverFriendResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ReceiverFriendResponse) GetSuccess() ErrCodeType {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return ErrCodeType_Success
}

type InvitePlayGameRequest struct {
	Userid           *int32              `protobuf:"varint,1,req,name=userid" json:"userid,omitempty"`
	Info             *InvitePlayGameInfo `protobuf:"bytes,2,req,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *InvitePlayGameRequest) Reset()                    { *m = InvitePlayGameRequest{} }
func (m *InvitePlayGameRequest) String() string            { return proto.CompactTextString(m) }
func (*InvitePlayGameRequest) ProtoMessage()               {}
func (*InvitePlayGameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *InvitePlayGameRequest) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *InvitePlayGameRequest) GetInfo() *InvitePlayGameInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type InvitePlayGameResponse struct {
	Success          *ErrCodeType `protobuf:"varint,1,req,name=success,enum=protobuf.ErrCodeType" json:"success,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *InvitePlayGameResponse) Reset()                    { *m = InvitePlayGameResponse{} }
func (m *InvitePlayGameResponse) String() string            { return proto.CompactTextString(m) }
func (*InvitePlayGameResponse) ProtoMessage()               {}
func (*InvitePlayGameResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *InvitePlayGameResponse) GetSuccess() ErrCodeType {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return ErrCodeType_Success
}

type ReceiverPlayGameRequest struct {
	Userid           *int32                `protobuf:"varint,1,req,name=userid" json:"userid,omitempty"`
	Info             *ReceiverPlayGameInfo `protobuf:"bytes,2,req,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *ReceiverPlayGameRequest) Reset()                    { *m = ReceiverPlayGameRequest{} }
func (m *ReceiverPlayGameRequest) String() string            { return proto.CompactTextString(m) }
func (*ReceiverPlayGameRequest) ProtoMessage()               {}
func (*ReceiverPlayGameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ReceiverPlayGameRequest) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *ReceiverPlayGameRequest) GetInfo() *ReceiverPlayGameInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReceiverPlayGameResponse struct {
	Success          *ErrCodeType `protobuf:"varint,1,req,name=success,enum=protobuf.ErrCodeType" json:"success,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ReceiverPlayGameResponse) Reset()                    { *m = ReceiverPlayGameResponse{} }
func (m *ReceiverPlayGameResponse) String() string            { return proto.CompactTextString(m) }
func (*ReceiverPlayGameResponse) ProtoMessage()               {}
func (*ReceiverPlayGameResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ReceiverPlayGameResponse) GetSuccess() ErrCodeType {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return ErrCodeType_Success
}

type FriendListRequest struct {
	Userid           *int32 `protobuf:"varint,1,req,name=userid" json:"userid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *FriendListRequest) Reset()                    { *m = FriendListRequest{} }
func (m *FriendListRequest) String() string            { return proto.CompactTextString(m) }
func (*FriendListRequest) ProtoMessage()               {}
func (*FriendListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *FriendListRequest) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

type FriendListRespose struct {
	Success          *ErrCodeType  `protobuf:"varint,1,req,name=success,enum=protobuf.ErrCodeType" json:"success,omitempty"`
	List             []*PlayerInfo `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *FriendListRespose) Reset()                    { *m = FriendListRespose{} }
func (m *FriendListRespose) String() string            { return proto.CompactTextString(m) }
func (*FriendListRespose) ProtoMessage()               {}
func (*FriendListRespose) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *FriendListRespose) GetSuccess() ErrCodeType {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return ErrCodeType_Success
}

func (m *FriendListRespose) GetList() []*PlayerInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type DeleteFriendRequest struct {
	Userid           *int32            `protobuf:"varint,1,req,name=userid" json:"userid,omitempty"`
	Info             *DeleteFriendInfo `protobuf:"bytes,2,req,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *DeleteFriendRequest) Reset()                    { *m = DeleteFriendRequest{} }
func (m *DeleteFriendRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteFriendRequest) ProtoMessage()               {}
func (*DeleteFriendRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *DeleteFriendRequest) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *DeleteFriendRequest) GetInfo() *DeleteFriendInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type DeleteFriendResponse struct {
	Success          *ErrCodeType `protobuf:"varint,1,req,name=success,enum=protobuf.ErrCodeType" json:"success,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *DeleteFriendResponse) Reset()                    { *m = DeleteFriendResponse{} }
func (m *DeleteFriendResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteFriendResponse) ProtoMessage()               {}
func (*DeleteFriendResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *DeleteFriendResponse) GetSuccess() ErrCodeType {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return ErrCodeType_Success
}

// 玩家聊天包
type ChatMessageInfo struct {
	SendUserid       *int32  `protobuf:"varint,1,req,name=sendUserid" json:"sendUserid,omitempty"`
	SendName         *string `protobuf:"bytes,2,req,name=sendName" json:"sendName,omitempty"`
	RoomId           *uint64 `protobuf:"varint,3,opt,name=roomId,def=0" json:"roomId,omitempty"`
	RecvUserid       *int32  `protobuf:"varint,4,opt,name=recvUserid,def=0" json:"recvUserid,omitempty"`
	RecvName         *string `protobuf:"bytes,5,opt,name=recvName" json:"recvName,omitempty"`
	Messageid        *string `protobuf:"bytes,6,req,name=messageid" json:"messageid,omitempty"`
	Message          *string `protobuf:"bytes,7,req,name=message" json:"message,omitempty"`
	Timestamp        *int32  `protobuf:"varint,8,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChatMessageInfo) Reset()                    { *m = ChatMessageInfo{} }
func (m *ChatMessageInfo) String() string            { return proto.CompactTextString(m) }
func (*ChatMessageInfo) ProtoMessage()               {}
func (*ChatMessageInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

const Default_ChatMessageInfo_RoomId uint64 = 0
const Default_ChatMessageInfo_RecvUserid int32 = 0

func (m *ChatMessageInfo) GetSendUserid() int32 {
	if m != nil && m.SendUserid != nil {
		return *m.SendUserid
	}
	return 0
}

func (m *ChatMessageInfo) GetSendName() string {
	if m != nil && m.SendName != nil {
		return *m.SendName
	}
	return ""
}

func (m *ChatMessageInfo) GetRoomId() uint64 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return Default_ChatMessageInfo_RoomId
}

func (m *ChatMessageInfo) GetRecvUserid() int32 {
	if m != nil && m.RecvUserid != nil {
		return *m.RecvUserid
	}
	return Default_ChatMessageInfo_RecvUserid
}

func (m *ChatMessageInfo) GetRecvName() string {
	if m != nil && m.RecvName != nil {
		return *m.RecvName
	}
	return ""
}

func (m *ChatMessageInfo) GetMessageid() string {
	if m != nil && m.Messageid != nil {
		return *m.Messageid
	}
	return ""
}

func (m *ChatMessageInfo) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *ChatMessageInfo) GetTimestamp() int32 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

// 玩家基本信息包
type PlayerInfo struct {
	Userid           *int32  `protobuf:"varint,1,req,name=userid" json:"userid,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Icon             *int32  `protobuf:"varint,3,req,name=icon" json:"icon,omitempty"`
	Sex              *int32  `protobuf:"varint,4,req,name=sex" json:"sex,omitempty"`
	Autograph        *string `protobuf:"bytes,5,req,name=autograph" json:"autograph,omitempty"`
	Grade            *int32  `protobuf:"varint,6,req,name=grade" json:"grade,omitempty"`
	Gnum             *int32  `protobuf:"varint,7,req,name=gnum" json:"gnum,omitempty"`
	Gsnum            *int32  `protobuf:"varint,8,req,name=gsnum" json:"gsnum,omitempty"`
	Gfnum            *int32  `protobuf:"varint,9,req,name=gfnum" json:"gfnum,omitempty"`
	Gdnum            *int32  `protobuf:"varint,10,req,name=gdnum" json:"gdnum,omitempty"`
	Fgsnum           *int32  `protobuf:"varint,11,req,name=fgsnum" json:"fgsnum,omitempty"`
	Fgfnum           *int32  `protobuf:"varint,12,req,name=fgfnum" json:"fgfnum,omitempty"`
	Fgdnum           *int32  `protobuf:"varint,13,req,name=fgdnum" json:"fgdnum,omitempty"`
	Money            *int32  `protobuf:"varint,14,req,name=money" json:"money,omitempty"`
	Status           *int32  `protobuf:"varint,15,req,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerInfo) Reset()                    { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()               {}
func (*PlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *PlayerInfo) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *PlayerInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PlayerInfo) GetIcon() int32 {
	if m != nil && m.Icon != nil {
		return *m.Icon
	}
	return 0
}

func (m *PlayerInfo) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *PlayerInfo) GetAutograph() string {
	if m != nil && m.Autograph != nil {
		return *m.Autograph
	}
	return ""
}

func (m *PlayerInfo) GetGrade() int32 {
	if m != nil && m.Grade != nil {
		return *m.Grade
	}
	return 0
}

func (m *PlayerInfo) GetGnum() int32 {
	if m != nil && m.Gnum != nil {
		return *m.Gnum
	}
	return 0
}

func (m *PlayerInfo) GetGsnum() int32 {
	if m != nil && m.Gsnum != nil {
		return *m.Gsnum
	}
	return 0
}

func (m *PlayerInfo) GetGfnum() int32 {
	if m != nil && m.Gfnum != nil {
		return *m.Gfnum
	}
	return 0
}

func (m *PlayerInfo) GetGdnum() int32 {
	if m != nil && m.Gdnum != nil {
		return *m.Gdnum
	}
	return 0
}

func (m *PlayerInfo) GetFgsnum() int32 {
	if m != nil && m.Fgsnum != nil {
		return *m.Fgsnum
	}
	return 0
}

func (m *PlayerInfo) GetFgfnum() int32 {
	if m != nil && m.Fgfnum != nil {
		return *m.Fgfnum
	}
	return 0
}

func (m *PlayerInfo) GetFgdnum() int32 {
	if m != nil && m.Fgdnum != nil {
		return *m.Fgdnum
	}
	return 0
}

func (m *PlayerInfo) GetMoney() int32 {
	if m != nil && m.Money != nil {
		return *m.Money
	}
	return 0
}

func (m *PlayerInfo) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

// 好友邀请信息
type InviteFriendInfo struct {
	InviterUserid    *int32  `protobuf:"varint,1,req,name=inviterUserid" json:"inviterUserid,omitempty"`
	InviterName      *string `protobuf:"bytes,2,req,name=inviterName" json:"inviterName,omitempty"`
	ReceiverUserid   *int32  `protobuf:"varint,3,req,name=receiverUserid" json:"receiverUserid,omitempty"`
	ReceiverName     *string `protobuf:"bytes,4,req,name=receiverName" json:"receiverName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *InviteFriendInfo) Reset()                    { *m = InviteFriendInfo{} }
func (m *InviteFriendInfo) String() string            { return proto.CompactTextString(m) }
func (*InviteFriendInfo) ProtoMessage()               {}
func (*InviteFriendInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *InviteFriendInfo) GetInviterUserid() int32 {
	if m != nil && m.InviterUserid != nil {
		return *m.InviterUserid
	}
	return 0
}

func (m *InviteFriendInfo) GetInviterName() string {
	if m != nil && m.InviterName != nil {
		return *m.InviterName
	}
	return ""
}

func (m *InviteFriendInfo) GetReceiverUserid() int32 {
	if m != nil && m.ReceiverUserid != nil {
		return *m.ReceiverUserid
	}
	return 0
}

func (m *InviteFriendInfo) GetReceiverName() string {
	if m != nil && m.ReceiverName != nil {
		return *m.ReceiverName
	}
	return ""
}

// 好友是否同意的信息
type ReceiverFriendInfo struct {
	InviterUserid    *int32  `protobuf:"varint,1,req,name=inviterUserid" json:"inviterUserid,omitempty"`
	InviterName      *string `protobuf:"bytes,2,req,name=inviterName" json:"inviterName,omitempty"`
	ReceiverUserid   *int32  `protobuf:"varint,3,req,name=receiverUserid" json:"receiverUserid,omitempty"`
	ReceiverName     *string `protobuf:"bytes,4,req,name=receiverName" json:"receiverName,omitempty"`
	IsAgree          *bool   `protobuf:"varint,5,req,name=isAgree" json:"isAgree,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReceiverFriendInfo) Reset()                    { *m = ReceiverFriendInfo{} }
func (m *ReceiverFriendInfo) String() string            { return proto.CompactTextString(m) }
func (*ReceiverFriendInfo) ProtoMessage()               {}
func (*ReceiverFriendInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *ReceiverFriendInfo) GetInviterUserid() int32 {
	if m != nil && m.InviterUserid != nil {
		return *m.InviterUserid
	}
	return 0
}

func (m *ReceiverFriendInfo) GetInviterName() string {
	if m != nil && m.InviterName != nil {
		return *m.InviterName
	}
	return ""
}

func (m *ReceiverFriendInfo) GetReceiverUserid() int32 {
	if m != nil && m.ReceiverUserid != nil {
		return *m.ReceiverUserid
	}
	return 0
}

func (m *ReceiverFriendInfo) GetReceiverName() string {
	if m != nil && m.ReceiverName != nil {
		return *m.ReceiverName
	}
	return ""
}

func (m *ReceiverFriendInfo) GetIsAgree() bool {
	if m != nil && m.IsAgree != nil {
		return *m.IsAgree
	}
	return false
}

// 邀请对战信息
type InvitePlayGameInfo struct {
	InviterUserid    *int32  `protobuf:"varint,1,req,name=inviterUserid" json:"inviterUserid,omitempty"`
	InviterName      *string `protobuf:"bytes,2,req,name=inviterName" json:"inviterName,omitempty"`
	ReceiverUserid   *int32  `protobuf:"varint,3,req,name=receiverUserid" json:"receiverUserid,omitempty"`
	ReceiverName     *string `protobuf:"bytes,4,req,name=receiverName" json:"receiverName,omitempty"`
	RoomId           *uint64 `protobuf:"varint,5,req,name=roomId" json:"roomId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *InvitePlayGameInfo) Reset()                    { *m = InvitePlayGameInfo{} }
func (m *InvitePlayGameInfo) String() string            { return proto.CompactTextString(m) }
func (*InvitePlayGameInfo) ProtoMessage()               {}
func (*InvitePlayGameInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *InvitePlayGameInfo) GetInviterUserid() int32 {
	if m != nil && m.InviterUserid != nil {
		return *m.InviterUserid
	}
	return 0
}

func (m *InvitePlayGameInfo) GetInviterName() string {
	if m != nil && m.InviterName != nil {
		return *m.InviterName
	}
	return ""
}

func (m *InvitePlayGameInfo) GetReceiverUserid() int32 {
	if m != nil && m.ReceiverUserid != nil {
		return *m.ReceiverUserid
	}
	return 0
}

func (m *InvitePlayGameInfo) GetReceiverName() string {
	if m != nil && m.ReceiverName != nil {
		return *m.ReceiverName
	}
	return ""
}

func (m *InvitePlayGameInfo) GetRoomId() uint64 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

// 是否接受对战信息
type ReceiverPlayGameInfo struct {
	InviterUserid    *int32  `protobuf:"varint,1,req,name=inviterUserid" json:"inviterUserid,omitempty"`
	InviterName      *string `protobuf:"bytes,2,req,name=inviterName" json:"inviterName,omitempty"`
	ReceiverUserid   *int32  `protobuf:"varint,3,req,name=receiverUserid" json:"receiverUserid,omitempty"`
	ReceiverName     *string `protobuf:"bytes,4,req,name=receiverName" json:"receiverName,omitempty"`
	RoomId           *uint64 `protobuf:"varint,5,req,name=roomId" json:"roomId,omitempty"`
	BlackUserid      *int32  `protobuf:"varint,6,req,name=blackUserid" json:"blackUserid,omitempty"`
	WhiteUserid      *int32  `protobuf:"varint,7,req,name=whiteUserid" json:"whiteUserid,omitempty"`
	IsAgree          *bool   `protobuf:"varint,8,req,name=isAgree" json:"isAgree,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReceiverPlayGameInfo) Reset()                    { *m = ReceiverPlayGameInfo{} }
func (m *ReceiverPlayGameInfo) String() string            { return proto.CompactTextString(m) }
func (*ReceiverPlayGameInfo) ProtoMessage()               {}
func (*ReceiverPlayGameInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ReceiverPlayGameInfo) GetInviterUserid() int32 {
	if m != nil && m.InviterUserid != nil {
		return *m.InviterUserid
	}
	return 0
}

func (m *ReceiverPlayGameInfo) GetInviterName() string {
	if m != nil && m.InviterName != nil {
		return *m.InviterName
	}
	return ""
}

func (m *ReceiverPlayGameInfo) GetReceiverUserid() int32 {
	if m != nil && m.ReceiverUserid != nil {
		return *m.ReceiverUserid
	}
	return 0
}

func (m *ReceiverPlayGameInfo) GetReceiverName() string {
	if m != nil && m.ReceiverName != nil {
		return *m.ReceiverName
	}
	return ""
}

func (m *ReceiverPlayGameInfo) GetRoomId() uint64 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *ReceiverPlayGameInfo) GetBlackUserid() int32 {
	if m != nil && m.BlackUserid != nil {
		return *m.BlackUserid
	}
	return 0
}

func (m *ReceiverPlayGameInfo) GetWhiteUserid() int32 {
	if m != nil && m.WhiteUserid != nil {
		return *m.WhiteUserid
	}
	return 0
}

func (m *ReceiverPlayGameInfo) GetIsAgree() bool {
	if m != nil && m.IsAgree != nil {
		return *m.IsAgree
	}
	return false
}

type MatchGameInfo struct {
	Success          *ErrCodeType `protobuf:"varint,1,req,name=success,enum=protobuf.ErrCodeType" json:"success,omitempty"`
	RoomId           *uint64      `protobuf:"varint,2,req,name=roomId" json:"roomId,omitempty"`
	BlackUserid      *int32       `protobuf:"varint,3,req,name=blackUserid" json:"blackUserid,omitempty"`
	WhiteUserid      *int32       `protobuf:"varint,4,req,name=whiteUserid" json:"whiteUserid,omitempty"`
	OtherInfo        *PlayerInfo  `protobuf:"bytes,5,req,name=otherInfo" json:"otherInfo,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *MatchGameInfo) Reset()                    { *m = MatchGameInfo{} }
func (m *MatchGameInfo) String() string            { return proto.CompactTextString(m) }
func (*MatchGameInfo) ProtoMessage()               {}
func (*MatchGameInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *MatchGameInfo) GetSuccess() ErrCodeType {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return ErrCodeType_Success
}

func (m *MatchGameInfo) GetRoomId() uint64 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

func (m *MatchGameInfo) GetBlackUserid() int32 {
	if m != nil && m.BlackUserid != nil {
		return *m.BlackUserid
	}
	return 0
}

func (m *MatchGameInfo) GetWhiteUserid() int32 {
	if m != nil && m.WhiteUserid != nil {
		return *m.WhiteUserid
	}
	return 0
}

func (m *MatchGameInfo) GetOtherInfo() *PlayerInfo {
	if m != nil {
		return m.OtherInfo
	}
	return nil
}

type DeleteFriendInfo struct {
	SelfUserid       *int32 `protobuf:"varint,1,req,name=selfUserid" json:"selfUserid,omitempty"`
	SelfName         *int32 `protobuf:"varint,2,req,name=selfName" json:"selfName,omitempty"`
	FriendUserid     *int32 `protobuf:"varint,3,req,name=friendUserid" json:"friendUserid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteFriendInfo) Reset()                    { *m = DeleteFriendInfo{} }
func (m *DeleteFriendInfo) String() string            { return proto.CompactTextString(m) }
func (*DeleteFriendInfo) ProtoMessage()               {}
func (*DeleteFriendInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *DeleteFriendInfo) GetSelfUserid() int32 {
	if m != nil && m.SelfUserid != nil {
		return *m.SelfUserid
	}
	return 0
}

func (m *DeleteFriendInfo) GetSelfName() int32 {
	if m != nil && m.SelfName != nil {
		return *m.SelfName
	}
	return 0
}

func (m *DeleteFriendInfo) GetFriendUserid() int32 {
	if m != nil && m.FriendUserid != nil {
		return *m.FriendUserid
	}
	return 0
}

// 对战逻辑包
type ChessPoint struct {
	X                *int32 `protobuf:"varint,1,req,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,2,req,name=y" json:"y,omitempty"`
	Z                *int32 `protobuf:"varint,3,req,name=z" json:"z,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ChessPoint) Reset()                    { *m = ChessPoint{} }
func (m *ChessPoint) String() string            { return proto.CompactTextString(m) }
func (*ChessPoint) ProtoMessage()               {}
func (*ChessPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *ChessPoint) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *ChessPoint) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *ChessPoint) GetZ() int32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

type ChessStack struct {
	Points           []*ChessPoint `protobuf:"bytes,1,rep,name=points" json:"points,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ChessStack) Reset()                    { *m = ChessStack{} }
func (m *ChessStack) String() string            { return proto.CompactTextString(m) }
func (*ChessStack) ProtoMessage()               {}
func (*ChessStack) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *ChessStack) GetPoints() []*ChessPoint {
	if m != nil {
		return m.Points
	}
	return nil
}

type ListChessStacks struct {
	Stacks           []*ChessStack `protobuf:"bytes,1,rep,name=stacks" json:"stacks,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ListChessStacks) Reset()                    { *m = ListChessStacks{} }
func (m *ListChessStacks) String() string            { return proto.CompactTextString(m) }
func (*ListChessStacks) ProtoMessage()               {}
func (*ListChessStacks) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *ListChessStacks) GetStacks() []*ChessStack {
	if m != nil {
		return m.Stacks
	}
	return nil
}

type NowChessNums struct {
	Bnum             *int32 `protobuf:"varint,1,req,name=bnum" json:"bnum,omitempty"`
	Wnum             *int32 `protobuf:"varint,2,req,name=wnum" json:"wnum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NowChessNums) Reset()                    { *m = NowChessNums{} }
func (m *NowChessNums) String() string            { return proto.CompactTextString(m) }
func (*NowChessNums) ProtoMessage()               {}
func (*NowChessNums) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *NowChessNums) GetBnum() int32 {
	if m != nil && m.Bnum != nil {
		return *m.Bnum
	}
	return 0
}

func (m *NowChessNums) GetWnum() int32 {
	if m != nil && m.Wnum != nil {
		return *m.Wnum
	}
	return 0
}

type NowChessCount struct {
	Bcount           *int32 `protobuf:"varint,1,req,name=bcount" json:"bcount,omitempty"`
	Wcount           *int32 `protobuf:"varint,2,req,name=wcount" json:"wcount,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NowChessCount) Reset()                    { *m = NowChessCount{} }
func (m *NowChessCount) String() string            { return proto.CompactTextString(m) }
func (*NowChessCount) ProtoMessage()               {}
func (*NowChessCount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *NowChessCount) GetBcount() int32 {
	if m != nil && m.Bcount != nil {
		return *m.Bcount
	}
	return 0
}

func (m *NowChessCount) GetWcount() int32 {
	if m != nil && m.Wcount != nil {
		return *m.Wcount
	}
	return 0
}

// 结算
type FinalStatistics struct {
	Nums             *NowChessNums  `protobuf:"bytes,1,req,name=nums" json:"nums,omitempty"`
	Counts           *NowChessCount `protobuf:"bytes,2,req,name=counts" json:"counts,omitempty"`
	Getscore         *int32         `protobuf:"varint,3,req,name=getscore" json:"getscore,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *FinalStatistics) Reset()                    { *m = FinalStatistics{} }
func (m *FinalStatistics) String() string            { return proto.CompactTextString(m) }
func (*FinalStatistics) ProtoMessage()               {}
func (*FinalStatistics) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *FinalStatistics) GetNums() *NowChessNums {
	if m != nil {
		return m.Nums
	}
	return nil
}

func (m *FinalStatistics) GetCounts() *NowChessCount {
	if m != nil {
		return m.Counts
	}
	return nil
}

func (m *FinalStatistics) GetGetscore() int32 {
	if m != nil && m.Getscore != nil {
		return *m.Getscore
	}
	return 0
}

type PutChessReq struct {
	Chess            *ChessPoint `protobuf:"bytes,1,req,name=chess" json:"chess,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *PutChessReq) Reset()                    { *m = PutChessReq{} }
func (m *PutChessReq) String() string            { return proto.CompactTextString(m) }
func (*PutChessReq) ProtoMessage()               {}
func (*PutChessReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *PutChessReq) GetChess() *ChessPoint {
	if m != nil {
		return m.Chess
	}
	return nil
}

type PutChessRes struct {
	Canput           *int32      `protobuf:"varint,1,req,name=canput" json:"canput,omitempty"`
	Chess            *ChessPoint `protobuf:"bytes,2,opt,name=chess" json:"chess,omitempty"`
	Clearstacks      *ChessStack `protobuf:"bytes,3,opt,name=clearstacks" json:"clearstacks,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *PutChessRes) Reset()                    { *m = PutChessRes{} }
func (m *PutChessRes) String() string            { return proto.CompactTextString(m) }
func (*PutChessRes) ProtoMessage()               {}
func (*PutChessRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *PutChessRes) GetCanput() int32 {
	if m != nil && m.Canput != nil {
		return *m.Canput
	}
	return 0
}

func (m *PutChessRes) GetChess() *ChessPoint {
	if m != nil {
		return m.Chess
	}
	return nil
}

func (m *PutChessRes) GetClearstacks() *ChessStack {
	if m != nil {
		return m.Clearstacks
	}
	return nil
}

// 游戏开局随机的玩家棋子类型
type RandomPlayerType struct {
	Type             *int32 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RandomPlayerType) Reset()                    { *m = RandomPlayerType{} }
func (m *RandomPlayerType) String() string            { return proto.CompactTextString(m) }
func (*RandomPlayerType) ProtoMessage()               {}
func (*RandomPlayerType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *RandomPlayerType) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

// 当前可下棋玩家类型
type NowCanPutType struct {
	Type             *int32 `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NowCanPutType) Reset()                    { *m = NowCanPutType{} }
func (m *NowCanPutType) String() string            { return proto.CompactTextString(m) }
func (*NowCanPutType) ProtoMessage()               {}
func (*NowCanPutType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *NowCanPutType) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

// 棋盘大小等设置
type ChessBoardRule struct {
	Size             *int32 `protobuf:"varint,1,req,name=size" json:"size,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ChessBoardRule) Reset()                    { *m = ChessBoardRule{} }
func (m *ChessBoardRule) String() string            { return proto.CompactTextString(m) }
func (*ChessBoardRule) ProtoMessage()               {}
func (*ChessBoardRule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *ChessBoardRule) GetSize() int32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

type ChessRuleSetReq struct {
	InviterUserid    *int32          `protobuf:"varint,1,req,name=inviterUserid" json:"inviterUserid,omitempty"`
	Sets             *ChessBoardRule `protobuf:"bytes,2,req,name=sets" json:"sets,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *ChessRuleSetReq) Reset()                    { *m = ChessRuleSetReq{} }
func (m *ChessRuleSetReq) String() string            { return proto.CompactTextString(m) }
func (*ChessRuleSetReq) ProtoMessage()               {}
func (*ChessRuleSetReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *ChessRuleSetReq) GetInviterUserid() int32 {
	if m != nil && m.InviterUserid != nil {
		return *m.InviterUserid
	}
	return 0
}

func (m *ChessRuleSetReq) GetSets() *ChessBoardRule {
	if m != nil {
		return m.Sets
	}
	return nil
}

// 当前可下棋玩家类型
type ChessRuleSetRes struct {
	Pass             *int32            `protobuf:"varint,1,req,name=pass" json:"pass,omitempty"`
	Sets             *ChessBoardRule   `protobuf:"bytes,2,opt,name=sets" json:"sets,omitempty"`
	Type             *RandomPlayerType `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *ChessRuleSetRes) Reset()                    { *m = ChessRuleSetRes{} }
func (m *ChessRuleSetRes) String() string            { return proto.CompactTextString(m) }
func (*ChessRuleSetRes) ProtoMessage()               {}
func (*ChessRuleSetRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *ChessRuleSetRes) GetPass() int32 {
	if m != nil && m.Pass != nil {
		return *m.Pass
	}
	return 0
}

func (m *ChessRuleSetRes) GetSets() *ChessBoardRule {
	if m != nil {
		return m.Sets
	}
	return nil
}

func (m *ChessRuleSetRes) GetType() *RandomPlayerType {
	if m != nil {
		return m.Type
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgEnum)(nil), "protobuf.MsgEnum")
	proto.RegisterType((*LoginRequest)(nil), "protobuf.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "protobuf.LoginResponse")
	proto.RegisterType((*PlayerRegisterRequest)(nil), "protobuf.PlayerRegisterRequest")
	proto.RegisterType((*PlayerRegisterResponse)(nil), "protobuf.PlayerRegisterResponse")
	proto.RegisterType((*ChatRequest)(nil), "protobuf.ChatRequest")
	proto.RegisterType((*ChatResponse)(nil), "protobuf.ChatResponse")
	proto.RegisterType((*MatchGameRequest)(nil), "protobuf.MatchGameRequest")
	proto.RegisterType((*MatchGameResponse)(nil), "protobuf.MatchGameResponse")
	proto.RegisterType((*InviteFriendRequest)(nil), "protobuf.InviteFriendRequest")
	proto.RegisterType((*InviteFriendResponse)(nil), "protobuf.InviteFriendResponse")
	proto.RegisterType((*ReceiverFriendRequest)(nil), "protobuf.ReceiverFriendRequest")
	proto.RegisterType((*ReceiverFriendResponse)(nil), "protobuf.ReceiverFriendResponse")
	proto.RegisterType((*InvitePlayGameRequest)(nil), "protobuf.InvitePlayGameRequest")
	proto.RegisterType((*InvitePlayGameResponse)(nil), "protobuf.InvitePlayGameResponse")
	proto.RegisterType((*ReceiverPlayGameRequest)(nil), "protobuf.ReceiverPlayGameRequest")
	proto.RegisterType((*ReceiverPlayGameResponse)(nil), "protobuf.ReceiverPlayGameResponse")
	proto.RegisterType((*FriendListRequest)(nil), "protobuf.FriendListRequest")
	proto.RegisterType((*FriendListRespose)(nil), "protobuf.FriendListRespose")
	proto.RegisterType((*DeleteFriendRequest)(nil), "protobuf.DeleteFriendRequest")
	proto.RegisterType((*DeleteFriendResponse)(nil), "protobuf.DeleteFriendResponse")
	proto.RegisterType((*ChatMessageInfo)(nil), "protobuf.ChatMessageInfo")
	proto.RegisterType((*PlayerInfo)(nil), "protobuf.PlayerInfo")
	proto.RegisterType((*InviteFriendInfo)(nil), "protobuf.InviteFriendInfo")
	proto.RegisterType((*ReceiverFriendInfo)(nil), "protobuf.ReceiverFriendInfo")
	proto.RegisterType((*InvitePlayGameInfo)(nil), "protobuf.InvitePlayGameInfo")
	proto.RegisterType((*ReceiverPlayGameInfo)(nil), "protobuf.ReceiverPlayGameInfo")
	proto.RegisterType((*MatchGameInfo)(nil), "protobuf.MatchGameInfo")
	proto.RegisterType((*DeleteFriendInfo)(nil), "protobuf.DeleteFriendInfo")
	proto.RegisterType((*ChessPoint)(nil), "protobuf.ChessPoint")
	proto.RegisterType((*ChessStack)(nil), "protobuf.ChessStack")
	proto.RegisterType((*ListChessStacks)(nil), "protobuf.ListChessStacks")
	proto.RegisterType((*NowChessNums)(nil), "protobuf.NowChessNums")
	proto.RegisterType((*NowChessCount)(nil), "protobuf.NowChessCount")
	proto.RegisterType((*FinalStatistics)(nil), "protobuf.FinalStatistics")
	proto.RegisterType((*PutChessReq)(nil), "protobuf.PutChessReq")
	proto.RegisterType((*PutChessRes)(nil), "protobuf.PutChessRes")
	proto.RegisterType((*RandomPlayerType)(nil), "protobuf.RandomPlayerType")
	proto.RegisterType((*NowCanPutType)(nil), "protobuf.NowCanPutType")
	proto.RegisterType((*ChessBoardRule)(nil), "protobuf.ChessBoardRule")
	proto.RegisterType((*ChessRuleSetReq)(nil), "protobuf.ChessRuleSetReq")
	proto.RegisterType((*ChessRuleSetRes)(nil), "protobuf.ChessRuleSetRes")
	proto.RegisterEnum("protobuf.ErrCodeType", ErrCodeType_name, ErrCodeType_value)
	proto.RegisterEnum("protobuf.MsgEnum_MsgType", MsgEnum_MsgType_name, MsgEnum_MsgType_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1705 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xd4, 0x58, 0x4b, 0x6f, 0xdb, 0xc6,
	0x16, 0xbe, 0xd4, 0xc3, 0xb2, 0x8f, 0x24, 0x5b, 0x1e, 0xbf, 0x94, 0xc7, 0xcd, 0xcd, 0xe5, 0x0d,
	0x82, 0x20, 0x37, 0xd7, 0x37, 0xf0, 0x22, 0x40, 0x83, 0x02, 0x45, 0xea, 0x3c, 0x60, 0xd4, 0x76,
	0x0c, 0x26, 0x5d, 0x76, 0x41, 0x53, 0x23, 0x89, 0xb1, 0x44, 0x2a, 0x24, 0xe5, 0x47, 0xb6, 0x5d,
	0xb5, 0x7f, 0xa0, 0xdb, 0x16, 0x05, 0xfa, 0x3b, 0x8a, 0xee, 0xda, 0x6e, 0xba, 0xec, 0xaa, 0xff,
	0xa4, 0x40, 0xcf, 0x99, 0x19, 0x6a, 0x86, 0x14, 0x15, 0x57, 0xe9, 0x26, 0xdd, 0x48, 0x33, 0xdf,
	0x79, 0xcc, 0x79, 0x0c, 0xcf, 0x99, 0x19, 0x68, 0x0e, 0x79, 0x1c, 0xbb, 0x3d, 0xbe, 0x3d, 0x8a,
	0xc2, 0x24, 0x64, 0x8b, 0xe2, 0xef, 0x78, 0xdc, 0xb5, 0xbf, 0xad, 0x41, 0xed, 0x20, 0xee, 0x3d,
	0x09, 0xc6, 0x43, 0xfb, 0x2b, 0x39, 0x7e, 0x79, 0x31, 0xe2, 0xec, 0x3a, 0xb4, 0x8f, 0x06, 0xee,
	0x05, 0x8f, 0x1c, 0xde, 0xf3, 0xe3, 0x84, 0xfe, 0x5f, 0x8f, 0x79, 0x9c, 0xbc, 0x74, 0x7b, 0x2d,
	0x8b, 0xfd, 0x13, 0xae, 0xe4, 0xa9, 0xf1, 0x28, 0x0c, 0x62, 0x4e, 0xe4, 0x12, 0x5b, 0x83, 0x95,
	0xfd, 0xb0, 0xe7, 0x07, 0x86, 0x4c, 0x99, 0xad, 0x43, 0x4b, 0x81, 0x9a, 0xb5, 0xc2, 0x18, 0x2c,
	0xef, 0xf6, 0xdd, 0xc4, 0xe0, 0xac, 0x92, 0xb8, 0xc4, 0x34, 0xe3, 0x02, 0xdb, 0x82, 0xb5, 0x03,
	0x37, 0xf1, 0xfa, 0xcf, 0xdc, 0x21, 0x37, 0xb8, 0x6b, 0xac, 0x0d, 0xeb, 0x06, 0x41, 0x8b, 0x2c,
	0xb2, 0xab, 0xb0, 0xb9, 0x17, 0x9c, 0xfa, 0x09, 0x7f, 0x1a, 0xf9, 0x3c, 0xe8, 0x18, 0x52, 0x4b,
	0xec, 0x1a, 0x6c, 0x65, 0x69, 0x5a, 0x10, 0xc8, 0x79, 0x87, 0x7b, 0xdc, 0x3f, 0xe5, 0xd1, 0x94,
	0x68, 0x9d, 0x9c, 0xcf, 0x53, 0xb5, 0x70, 0x83, 0x84, 0xa5, 0x66, 0x8a, 0x50, 0xce, 0xda, 0x26,
	0x09, 0xe7, 0xa9, 0x5a, 0x78, 0x99, 0xdd, 0x80, 0xab, 0xa9, 0xee, 0x02, 0xf1, 0x15, 0xf6, 0x2f,
	0xb8, 0x36, 0x4d, 0xd7, 0x0a, 0x5a, 0x14, 0x0d, 0x69, 0xd4, 0x3e, 0xe6, 0xc5, 0x10, 0x5d, 0x65,
	0x57, 0x60, 0xc3, 0xa4, 0x68, 0x21, 0x46, 0x81, 0x7a, 0xcc, 0x07, 0xbc, 0x20, 0x50, 0x6b, 0x14,
	0xa8, 0x2c, 0x4d, 0x0b, 0xae, 0xb3, 0x4d, 0x60, 0xbb, 0x7d, 0xdc, 0x59, 0xce, 0x78, 0xc0, 0x5f,
	0x70, 0x5a, 0x8f, 0xf0, 0x8d, 0x69, 0x3c, 0x26, 0x7c, 0x93, 0xb2, 0x7d, 0x34, 0x4e, 0x24, 0x49,
	0xf2, 0x6e, 0x65, 0x31, 0xc1, 0xd7, 0x96, 0xf2, 0x6e, 0x72, 0x20, 0x37, 0xed, 0x5e, 0xd0, 0x0d,
	0x09, 0xe7, 0x6c, 0x15, 0x9a, 0x72, 0xdf, 0xa5, 0x50, 0x97, 0xf6, 0x85, 0x99, 0xc8, 0x94, 0xd0,
	0x23, 0x7f, 0xb3, 0x69, 0x4a, 0x49, 0x7d, 0x22, 0x65, 0x93, 0x90, 0x92, 0x7c, 0x72, 0x37, 0x1f,
	0xe0, 0x94, 0xf8, 0x8a, 0xb6, 0xf0, 0x64, 0xab, 0xa5, 0xe8, 0x09, 0x59, 0x60, 0x46, 0x28, 0x25,
	0x0c, 0x30, 0x17, 0x6b, 0x8e, 0x1b, 0x74, 0xc2, 0xa1, 0xb4, 0x99, 0xbe, 0x2b, 0x22, 0xfc, 0x68,
	0xb1, 0x0d, 0x68, 0x1d, 0x86, 0x67, 0xbb, 0x6e, 0x80, 0x9e, 0xa7, 0xf0, 0x4f, 0x16, 0x6a, 0x62,
	0x4f, 0xfd, 0xc0, 0x1d, 0xbc, 0x48, 0xdc, 0x04, 0x93, 0xe4, 0x7b, 0x22, 0x1c, 0x3f, 0x5b, 0xf6,
	0x4b, 0x68, 0x98, 0x1f, 0x14, 0x6a, 0xae, 0xb9, 0x9e, 0x17, 0x8e, 0x83, 0xa4, 0x6d, 0xdd, 0x2c,
	0xdd, 0x59, 0x72, 0xd2, 0x29, 0x46, 0x6e, 0x61, 0xe4, 0xc6, 0xf1, 0x59, 0xa7, 0x5d, 0x12, 0x04,
	0x35, 0xc3, 0x28, 0x57, 0x4e, 0xfc, 0xa0, 0xd3, 0x2e, 0x23, 0x5a, 0x75, 0xc4, 0xd8, 0x7e, 0x05,
	0xcd, 0xcc, 0x17, 0xc9, 0xfe, 0x0f, 0xb5, 0x78, 0xec, 0x79, 0x18, 0x75, 0xa1, 0x76, 0x79, 0x67,
	0x63, 0x3b, 0x2d, 0x14, 0xdb, 0x4f, 0xa2, 0x68, 0x37, 0xec, 0x70, 0xb2, 0xd6, 0x49, 0xb9, 0xd8,
	0x1d, 0xa8, 0xf8, 0xe8, 0xae, 0x58, 0xab, 0xbe, 0xb3, 0xae, 0xb9, 0x75, 0x96, 0x1c, 0xc1, 0x61,
	0x7f, 0x63, 0xc1, 0x46, 0x61, 0x41, 0x79, 0x8b, 0x2f, 0x68, 0x73, 0x80, 0x91, 0x56, 0x9e, 0x88,
	0xb1, 0xe1, 0x5f, 0x39, 0xef, 0x9f, 0xef, 0x85, 0x41, 0xbb, 0x22, 0xfd, 0xa3, 0x31, 0x6b, 0x41,
	0x39, 0xe6, 0xe7, 0xed, 0xaa, 0x80, 0x68, 0x88, 0xdf, 0xe6, 0x92, 0x3b, 0x4e, 0xc2, 0x5e, 0xe4,
	0x8e, 0xfa, 0xed, 0x05, 0xa1, 0x40, 0x03, 0xb6, 0x0b, 0x9b, 0xc5, 0x55, 0x6d, 0xfe, 0xc0, 0xa0,
	0x99, 0xe3, 0x98, 0x47, 0xbe, 0x4c, 0x43, 0xd5, 0x51, 0x33, 0xfb, 0x43, 0xa8, 0x1b, 0xe5, 0x8e,
	0xfd, 0x4f, 0xc5, 0xcf, 0x12, 0xf1, 0xbb, 0xa2, 0x95, 0xe6, 0x76, 0xbf, 0x0a, 0xe2, 0x67, 0xd0,
	0x30, 0x0b, 0xe3, 0xfc, 0x66, 0xa1, 0xff, 0x89, 0x8f, 0xad, 0x20, 0x71, 0x87, 0x23, 0x65, 0x99,
	0x06, 0xec, 0xbb, 0xc6, 0xf6, 0x4e, 0x2d, 0xd4, 0x8e, 0x58, 0x19, 0x47, 0x1e, 0xc3, 0xea, 0x54,
	0xd5, 0x9d, 0xdb, 0x1e, 0x74, 0x68, 0xad, 0xa0, 0x42, 0xcf, 0x5a, 0x94, 0x6d, 0x67, 0xb6, 0xdb,
	0x55, 0xad, 0x3c, 0x5f, 0x01, 0x54, 0xbc, 0x9e, 0xc1, 0x7a, 0x51, 0x91, 0x9f, 0xdf, 0x4e, 0x37,
	0x5f, 0x4b, 0x2e, 0xb3, 0xf4, 0x7e, 0xc6, 0xd2, 0xeb, 0x5a, 0xfd, 0x74, 0x49, 0x52, 0xb6, 0xee,
	0xc1, 0x66, 0x71, 0x57, 0x79, 0x27, 0x6b, 0x0b, 0x3b, 0xd0, 0xfc, 0xd6, 0x4e, 0x57, 0x49, 0x6d,
	0x6d, 0x71, 0x1b, 0x9b, 0xdf, 0x5a, 0x3e, 0x5d, 0x71, 0x2f, 0xb3, 0x77, 0x27, 0x63, 0xef, 0x8d,
	0xe9, 0xe8, 0x16, 0x58, 0xfc, 0x89, 0xee, 0xe9, 0x7f, 0xdd, 0xe6, 0xff, 0xc2, 0xea, 0x54, 0x97,
	0x9d, 0xf9, 0xa9, 0x04, 0x59, 0x66, 0x5c, 0xf3, 0x1d, 0x4b, 0xed, 0x00, 0xe5, 0xd1, 0xe7, 0xf2,
	0xec, 0x52, 0x4b, 0x1c, 0xf4, 0x51, 0x15, 0x74, 0xf3, 0xf9, 0x3f, 0xaa, 0x7c, 0x53, 0xd3, 0x1f,
	0x55, 0xd1, 0x81, 0x60, 0xfe, 0x20, 0xfe, 0x6e, 0xc9, 0x73, 0x9e, 0x51, 0xe7, 0xf0, 0xfc, 0x03,
	0x31, 0x2a, 0xfd, 0xd4, 0x34, 0xd4, 0x40, 0xf0, 0xa4, 0xb2, 0x48, 0xb3, 0x43, 0xdd, 0x16, 0x26,
	0x73, 0xec, 0xea, 0x0b, 0x51, 0x18, 0x0e, 0xf7, 0xa8, 0x35, 0x58, 0x77, 0x2a, 0x0f, 0xad, 0xfb,
	0x8e, 0x02, 0xd8, 0xbf, 0x01, 0x22, 0xee, 0x9d, 0x2a, 0xb5, 0x15, 0x24, 0x57, 0x89, 0x6c, 0x80,
	0xa4, 0x99, 0x66, 0x42, 0x73, 0x15, 0x19, 0x50, 0x73, 0x3a, 0xa7, 0xb2, 0xa9, 0xce, 0xcf, 0x28,
	0xad, 0xda, 0xc6, 0x04, 0xa0, 0x06, 0xa6, 0x26, 0xed, 0x9a, 0x6c, 0x60, 0x6a, 0x9a, 0x2d, 0xb7,
	0x8b, 0xf9, 0x72, 0xfb, 0x5b, 0x09, 0x40, 0x27, 0x6f, 0x66, 0x7e, 0x8a, 0xba, 0x60, 0xda, 0xed,
	0xca, 0xd3, 0xdd, 0xae, 0x32, 0xa3, 0xdb, 0x55, 0x73, 0xdd, 0x0e, 0x0f, 0x33, 0x55, 0x1c, 0x74,
	0xb8, 0x70, 0xa8, 0xea, 0xc8, 0x09, 0x69, 0xee, 0xe1, 0x5d, 0x40, 0x78, 0x82, 0x9a, 0x69, 0x2c,
	0x38, 0x63, 0x02, 0x17, 0x15, 0x67, 0x9c, 0xa2, 0x5d, 0x42, 0x97, 0x14, 0xda, 0x4d, 0xd1, 0x0e,
	0xa1, 0xa0, 0x50, 0x9a, 0x90, 0x6f, 0x5d, 0xa9, 0xa2, 0x2e, 0x7d, 0x93, 0x33, 0x89, 0x0b, 0x25,
	0x8d, 0x14, 0xef, 0x4e, 0x70, 0xa1, 0xa6, 0x99, 0xe2, 0x1d, 0xa5, 0x7d, 0x18, 0x06, 0xfc, 0xa2,
	0xbd, 0x2c, 0xb5, 0x8b, 0x09, 0x71, 0x63, 0x44, 0x93, 0x71, 0xdc, 0x5e, 0x91, 0xdc, 0x72, 0x66,
	0x7f, 0x67, 0x41, 0x2b, 0xdf, 0x19, 0xd8, 0x2d, 0x68, 0xfa, 0x02, 0x8b, 0x32, 0x9b, 0x2c, 0x0b,
	0xb2, 0x9b, 0x50, 0x57, 0x80, 0xb1, 0xd5, 0x4c, 0x88, 0xdd, 0x86, 0xe5, 0x48, 0xd5, 0x13, 0xa5,
	0x48, 0x26, 0x23, 0x87, 0x32, 0x1b, 0x1a, 0x29, 0x22, 0x54, 0x55, 0x84, 0xaa, 0x0c, 0x66, 0xff,
	0x60, 0x01, 0x9b, 0x6e, 0x0c, 0xef, 0xa3, 0xa9, 0xb4, 0xd9, 0xfd, 0xf8, 0x51, 0x2f, 0xe2, 0x5c,
	0xec, 0xa8, 0x45, 0x27, 0x9d, 0xda, 0xdf, 0xa3, 0x13, 0xd3, 0xfd, 0xe2, 0xbd, 0x74, 0x62, 0x73,
	0x52, 0x29, 0xc8, 0x87, 0x4a, 0x5a, 0x26, 0xec, 0xaf, 0x4b, 0xb0, 0x5e, 0xd4, 0x42, 0xfe, 0x4e,
	0x4e, 0x90, 0x15, 0xc7, 0x03, 0xd7, 0x3b, 0x51, 0x0b, 0xc8, 0xaf, 0xdb, 0x84, 0x88, 0xe3, 0xac,
	0x8f, 0x36, 0x29, 0x0e, 0xf9, 0xa9, 0x9b, 0x90, 0x99, 0xe5, 0xc5, 0x6c, 0x96, 0x7f, 0xb1, 0xa0,
	0x99, 0xb9, 0x03, 0xbd, 0xd3, 0xd9, 0x58, 0x19, 0x5e, 0x7a, 0x9b, 0xe1, 0xe5, 0x4b, 0x0d, 0xaf,
	0x4c, 0x1b, 0xbe, 0x03, 0x4b, 0x61, 0xd2, 0x97, 0x15, 0x55, 0xc4, 0x65, 0x56, 0xab, 0xd4, 0x6c,
	0x76, 0x04, 0xad, 0x7c, 0xab, 0x93, 0x7d, 0x68, 0xd0, 0xcd, 0xf7, 0xa1, 0x14, 0x91, 0x7d, 0x68,
	0xd0, 0x9d, 0xe4, 0xb9, 0xea, 0x4c, 0xe6, 0x94, 0xbc, 0xae, 0xd0, 0x94, 0x71, 0x24, 0x83, 0xd9,
	0x0f, 0x00, 0xc4, 0x8d, 0xf7, 0x28, 0xf4, 0xf1, 0xa2, 0xd3, 0x00, 0xeb, 0x5c, 0x2d, 0x62, 0x9d,
	0xd3, 0xec, 0x42, 0x29, 0xb5, 0x2e, 0x68, 0xf6, 0x46, 0xa9, 0xb0, 0xde, 0xd8, 0x0f, 0x95, 0x1c,
	0xde, 0x10, 0xbd, 0x13, 0x76, 0x0f, 0x2f, 0x43, 0xa4, 0x80, 0x22, 0x9f, 0x3b, 0x15, 0x68, 0xed,
	0x8e, 0xe2, 0xb1, 0x3f, 0x82, 0x15, 0x3a, 0x81, 0x68, 0xf9, 0x98, 0x14, 0xc4, 0x62, 0x34, 0x43,
	0x81, 0x60, 0x73, 0x14, 0x0f, 0x1a, 0xdd, 0xa0, 0x5b, 0x2b, 0x11, 0x0e, 0xc7, 0xc3, 0x98, 0x7a,
	0xc5, 0x31, 0xd5, 0x68, 0x69, 0xb9, 0x18, 0x13, 0x76, 0x46, 0x98, 0xb4, 0x5f, 0x8c, 0x71, 0xe1,
	0x66, 0x2a, 0xb7, 0x9b, 0x5e, 0x52, 0x8f, 0xf5, 0x8d, 0x0f, 0x0b, 0xf6, 0xf1, 0xe4, 0xf2, 0x7a,
	0x26, 0x71, 0x75, 0x6b, 0x92, 0x33, 0xfb, 0x4b, 0x3c, 0x29, 0xe4, 0x2e, 0xc6, 0xec, 0x2e, 0xb6,
	0x45, 0x34, 0x42, 0x5d, 0x9d, 0x36, 0xb5, 0xe1, 0xa6, 0x89, 0x8e, 0xe0, 0xc1, 0x2d, 0xba, 0x20,
	0x14, 0xc5, 0xea, 0x90, 0xb3, 0x35, 0xcd, 0x2d, 0x0c, 0x73, 0x14, 0x1b, 0xa5, 0xb7, 0xc7, 0x93,
	0xd8, 0x0b, 0x23, 0xae, 0x62, 0x3f, 0x99, 0xdb, 0x1f, 0x40, 0xdd, 0x78, 0xc3, 0x40, 0x3b, 0xaa,
	0x5e, 0x3f, 0xdd, 0xfc, 0xb3, 0x52, 0x20, 0x59, 0xec, 0x2f, 0x2c, 0x53, 0x56, 0x7c, 0x09, 0x9e,
	0x1b, 0x8c, 0xc6, 0x93, 0x38, 0xc8, 0x99, 0xd6, 0x59, 0xc2, 0x83, 0xc8, 0xdb, 0x75, 0xb2, 0x07,
	0x50, 0xf7, 0x06, 0xdc, 0x8d, 0x54, 0x1e, 0xcb, 0x85, 0x12, 0x32, 0x8f, 0x26, 0xa3, 0x7d, 0x1b,
	0x5a, 0xf9, 0xc7, 0x09, 0x4a, 0x5e, 0x82, 0xff, 0x69, 0x42, 0x69, 0x6c, 0xff, 0x47, 0x26, 0x6f,
	0xf2, 0x54, 0x51, 0xc8, 0x74, 0x8b, 0x5e, 0xf1, 0x70, 0x9d, 0x8f, 0x43, 0x37, 0xea, 0xd0, 0xa3,
	0x0f, 0x71, 0xc5, 0xfe, 0x9b, 0x09, 0x17, 0x8d, 0xf1, 0xa4, 0xbf, 0x92, 0x7b, 0x2d, 0xfa, 0x93,
	0x85, 0xf5, 0x1e, 0x2a, 0xe3, 0x93, 0xec, 0xb5, 0x73, 0xce, 0x4d, 0x16, 0x75, 0x04, 0x97, 0xfd,
	0xb9, 0x95, 0x5f, 0x47, 0x6c, 0x55, 0x7a, 0x28, 0x48, 0xcd, 0xa1, 0xb1, 0xa1, 0xd5, 0xba, 0x5c,
	0x2b, 0x1d, 0x93, 0x85, 0xdb, 0x32, 0xc0, 0xc6, 0x31, 0x39, 0x1f, 0x45, 0x19, 0x92, 0xbb, 0xbf,
	0x96, 0xa0, 0x6e, 0x94, 0x3f, 0x56, 0x87, 0xda, 0x0b, 0x59, 0x00, 0x5b, 0xff, 0xa0, 0xf7, 0x2d,
	0x87, 0x8f, 0xb8, 0x9b, 0xf0, 0x8e, 0x78, 0x81, 0x41, 0xc6, 0x30, 0x6a, 0xd1, 0xbb, 0xd0, 0xea,
	0x23, 0xf9, 0xf8, 0xf1, 0xe4, 0x1c, 0xf7, 0xb9, 0x84, 0x4b, 0xf4, 0xa8, 0xa7, 0xe0, 0xc3, 0xd0,
	0xa4, 0x94, 0xb1, 0x22, 0x5e, 0x57, 0x94, 0xe7, 0xd1, 0x91, 0x78, 0x09, 0x41, 0x0e, 0x51, 0x9f,
	0x25, 0x47, 0x85, 0x2d, 0x03, 0x1c, 0x5c, 0xc4, 0xaf, 0x07, 0x72, 0x5e, 0xa5, 0xa5, 0xa5, 0xad,
	0xcf, 0xbb, 0xdd, 0x81, 0x1f, 0x70, 0x89, 0x2f, 0xd0, 0xd2, 0x0e, 0xd6, 0xe1, 0xec, 0x02, 0x35,
	0x7a, 0x1a, 0x3c, 0x22, 0x4f, 0x8f, 0x70, 0xd3, 0xf0, 0xe4, 0x69, 0x18, 0x0d, 0x5d, 0x45, 0x13,
	0xef, 0xab, 0x52, 0x15, 0xfd, 0xfa, 0x41, 0x8f, 0x5a, 0x82, 0xa4, 0x2d, 0xd1, 0x43, 0xa5, 0x3c,
	0x0c, 0x44, 0xfa, 0xee, 0xb3, 0xef, 0x0f, 0x7d, 0x25, 0x0c, 0x9a, 0x81, 0x17, 0x32, 0xd4, 0xc9,
	0x69, 0xa9, 0x7d, 0x9f, 0xbb, 0xa7, 0x9c, 0x6c, 0x93, 0x94, 0xc6, 0x1f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x00, 0xc9, 0x5a, 0x94, 0xcd, 0x16, 0x00, 0x00,
}
